def PatternCount(text, pattern):
    count = 0
    for i in range(0, (len(text) - len(pattern) + 1)):
        if text[i:i+len(pattern)] == pattern:
       		count = count + 1
    return count

Input = "AGGAGCTTGTCTAGGGTTTGCATAACATACAGTGCCAGGAGCTTGTAGGAGCTTGTGCATAACATCTAGGGTTTAGGAGCTTGTAGGAGCTTGTGCATAACATACAGTGCCTTATCACGAGGAGCTTGTGCATAACATTTATCACGAGGAGCTTGTACAGTGCCGCATAACATAGGAGCTTGTTTATCACGCTAGGGTTTCTAGGGTTTACAGTGCCGCATAACATTTATCACGAGGAGCTTGTAGGAGCTTGTCTAGGGTTTTTATCACGCTAGGGTTTACAGTGCCACAGTGCCACAGTGCCGCATAACATTTATCACGCTAGGGTTTTTATCACGCTAGGGTTTTTATCACGACAGTGCCACAGTGCCTTATCACGAGGAGCTTGTACAGTGCCACAGTGCCGCATAACATGCATAACATACAGTGCCCTAGGGTTTACAGTGCCGCATAACATACAGTGCCACAGTGCCGCATAACATGCATAACATAGGAGCTTGTGCATAACATTTATCACGAGGAGCTTGTTTATCACGAGGAGCTTGTTTATCACGAGGAGCTTGTGCATAACATACAGTGCCAGGAGCTTGTTTATCACGAGGAGCTTGTAGGAGCTTGTAGGAGCTTGTGCATAACATGCATAACATCTAGGGTTTACAGTGCCCTAGGGTTTTTATCACGAGGAGCTTGTCTAGGGTTTTTATCACGAGGAGCTTGTGCATAACATCTAGGGTTTAGGAGCTTGTAGGAGCTTGTAGGAGCTTGTTTATCACGCTAGGGTTTACAGTGCCGCATAACATAGGAGCTTGTCTAGGGTTTGCATAACATAGGAGCTTGTTTATCACGTTATCACGCTAGGGTTTTTATCACGTTATCACGCTAGGGTTTTTATCACGTTATCACGTTATCACGTTATCACGTTATCACGACAGTGCC"

def FrequentSequence(text, x):
    maxcount = 0
    patternLength = int(x)
    maxPattern = []
    for i in range(0, (len(text) - patternLength + 1)):
        if PatternCount(text, text[i:i + patternLength]) > maxcount:
            maxcount = PatternCount(text, text[i:i+patternLength])
            maxPattern = []
            maxPattern.append(text[i:i + patternLength])
        elif PatternCount(text, text[i:i + patternLength]) == maxcount and text[i:i+patternLength] not in maxPattern:
            maxPattern.append(text[i:i + patternLength])
    print (maxPattern)
    
print (FrequentSequence(Input, 11))